package com.bartex.quizday.model.common

object MapOfCapital {
    val mapCapital = mapOf(
        "Kabul" to "Кабул",
        "Mariehamn" to "Мариехамн",
        "Tirana" to "Тирана",
        "Algiers" to "Алжир",
        "Pago Pago" to "Паго Паго",
        "Andorra" to "Андорра-ла-Велья",
        "Luanda" to "Луанда",
        "The Valley" to "Долина",
        "Saint John's" to "Сент-Джонс",
        "Buenos Aires" to "Буэнос-Айрес",
        "Yerevan" to "Ереван",
        "Oranjestad" to "Ораньестад",
        "Canberra" to "Канберра",
        "Vienna" to "Вена",
        "Baku" to "Баку",
        "Nassau" to "Нассау",
        "Manama" to "Манама",
        "Dhaka" to "Дакка",
        "Bridgetown" to "Бриджтаун",
        "Minsk" to "Минск",
        "Brussels" to "Брюссель",
        "Belmopan" to "Бельмопан",
        "Porto-Novo" to "Порто-Ново",
        "Hamilton" to "Гамильтон",
        "Thimphu" to "Тхимпху",
        "Sucre" to "Сукре",
        "Kralendijk" to "Кралендейк",
        "Sarajevo" to "Сараево",
        "Gaborone" to "Габороне",
        "Brasília" to "Бразилиа",
        "Diego Garcia" to "Диего-Гарсия",
        "Road Town" to "Род-Таун",
        "Charlotte Amalie" to "Шарлотта Амалия",
        "Bandar Seri Begawan" to "Бандар-Сери-Бегаван",
        "Sofia" to "София",
        "Ouagadougou" to "Уагодугу",
        "Bujumbura" to "Бужумбура",
        "Phnom Penh" to "Пномпень",
        "Yaoundé" to "Яунде",
        "Ottawa" to "Оттава",
        "Praia" to "Прая",
        "George Town" to "Джоржтаун",
        "Bangui" to "Банги",
        "N'Djamena" to "Нджамена",
        "Santiago" to "Сантьяго",
        "Beijing" to "Пекин",
        "Flying Fish Cove" to "Флаинг Фиш Ков",
        "West Island" to "Остров Запад",
        "Bogotá" to "Богота",
        "Moroni" to "Мороний",
        "Brazzaville" to "Браззавиль",
        "Kinshasa" to "Киншаса",
        "Avarua" to "Аваруа",
        "San José" to "Сан-Хосе",
        "Zagreb" to "Загреб",
        "Havana" to "Гавана",
        "Willemstad" to "Виллемстад",
        "Nicosia" to "Никосия",
        "Prague" to "Прага",
        "Copenhagen" to "Копенгаген",
        "Djibouti" to "Джибути",
        "Roseau" to "Розо",
        "Santo Domingo" to "Санто-Доминго",
        "Quito" to "Кито",
        "Cairo" to "Каир",
        "San Salvador" to "Сан-Сальвадор",
        "Malabo" to "Малабо",
        "Asmara" to "Асмэра",
        "Tallinn" to "Таллинн",
        "Addis Ababa" to "Аддис-Абеба",
        "Stanley" to "Стэнли",
        "Tórshavn" to "Торсхавн",
        "Suva" to "Сува",
        "Helsinki" to "Хельсинки",
        "Paris" to "Париж",
        "Cayenne" to "Кайенна",
        "Papeetē" to "Папеэтэ",
        "Port-aux-Français" to "Порт-о-Франсе",
        "Libreville" to "Либревиль",
        "Banjul" to "Банжул",
        "Tbilisi" to "Тбилиси",
        "Berlin" to "Берлин",
        "Accra" to "Аккра",
        "Gibraltar" to "Гибралтар",
        "Athens" to "Афины",
        "Nuuk" to "Нуук",
        "St. George's" to "Сент-Джорджес",
        "Basse-Terre" to "Басс-Терр",
        "Hagåtña" to "Хагатна",
        "Guatemala City" to "Гватемала",
        "St. Peter Port" to "Сент-Питер-Порт",
        "Conakry" to "Конакри",
        "Bissau" to "Бисау",
        "Georgetown" to "Джоржтаун",
        "Port-au-Prince" to "Порт-о-Пренс",
        "Rome" to "Рим",
        "Tegucigalpa" to "Тегусигальпа",
        "City of Victoria" to "Гонконг",
        "Budapest" to "Будапешт",
        "Reykjavík" to "Рейкьявик",
        "New Delhi" to "Нью-Дели",
        "Jakarta" to "Джакарта",
        "Yamoussoukro" to "Ямусукро",
        "Tehran" to "Тегеран",
        "Baghdad" to "Багдад ",
        "Dublin" to "Дублин",
        "Douglas" to "Дуглас",
        "Jerusalem" to "Иерусалим",
        "Rome" to "Рим",
        "Kingston" to "Кингстон",
        "Tokyo" to "Токио",
        "Saint Helier" to "Сент-Хелиер",
        "Amman" to "Амман",
        "Astana" to "Нур-Султан",
        "Nairobi" to "Найроби",
        "South Tarawa" to "Южная Тарава",
        "Kuwait City" to "Кувейт",
        "Bishkek" to "Бишкек",
        "Vientiane" to "Вьентьян",
        "Riga" to "Рига",
        "Beirut" to "Бейрут",
        "Maseru" to "Масеру",
        "Monrovia" to "Монровия",
        "Tripoli" to "Триполи",
        "Vaduz" to "Вадуц",
        "Vilnius" to "Вильнюс",
        "Luxembourg" to "Люксембург",
        "Skopje" to "Скопье",
        "Antananarivo" to "Антананариву",
        "Lilongwe" to "Лилонгве",
        "Kuala Lumpur" to "Куала-Лумпур",
        "Malé" to "Мале",
        "Bamako" to "Бамако",
        "Valletta" to "Валлетта",
        "Majuro" to "Маджуро",
        "Fort-de-France" to "Фор-де-Франс",
        "Nouakchott" to "Нуакшот",
        "Port Louis" to "Порт-Луи",
        "Mamoudzou" to "Мамудзу",
        "Mexico City" to "Мехико",
        "Palikir" to "Паликир",
        "Chișinău" to "Кишинёв",
        "Monaco" to "Монако",
        "Ulan Bator" to "Улан-Батор",
        "Podgorica" to "Подгорица",
        "Plymouth" to "Плимут",
        "Rabat" to "Рабат",
        "Maputo" to "Мапуту",
        "Naypyidaw" to "Нейпьидо",
        "Windhoek" to "Виндхук",
        "Yaren" to "Ярен",
        "Kathmandu" to "Катманду",
        "Amsterdam" to "Амстердам",
        "Nouméa" to "Нумеа",
        "Wellington" to "Веллингтон",
        "Managua" to "Манагуя",
        "Niamey" to "Ниамей",
        "Abuja" to "Абуджа",
        "Alofi" to "Алофи",
        "Kingston" to "Кингстон",
        "Pyongyang" to "Пхеньян",
        "Saipan" to "Сайпан",
        "Oslo" to "Осло",
        "Muscat" to "Маскат",
        "Islamabad" to "Исламабад",
        "Ngerulmud" to "Нгерулмуд",
        "Ramallah" to "Рамаллах",
        "Panama City" to "Панама",
        "Port Moresby" to "Порт-Морсби",
        "Asunción" to "Асунсьон",
        "Lima" to "Лима",
        "Manila" to "Манила",
        "Adamstown" to "Адамстаун",
        "Warsaw" to "Варшава",
        "Lisbon" to "Лиссабон",
        "San Juan" to "Сан-Хуан",
        "Doha" to "Доха",
        "Pristina" to "Приштина",
        "Saint-Denis" to "Сен-Дени",
        "Bucharest" to "Бухарест",
        "Moscow" to "Москва",
        "Kigali" to "Кигали",
        "Gustavia" to "Густавия",
        "Jamestown" to "Джеймстаун",
        "Basseterre" to "Бастер",
        "Castries" to "Кастри",
        "Marigot" to "Мариго",
        "Saint-Pierre" to "Сен-Пьер",
        "Kingstown" to "Кингстаун",
        "Apia" to "Апиа",
        "City of San Marino" to "Сан-Марино",
        "São Tomé" to "Сан-Томе",
        "Riyadh" to "Эр-Рияд",
        "Dakar" to "Дакар",
        "Belgrade" to "Белград",
        "Victoria" to "Виктория",
        "Freetown" to "Фритаун",
        "Singapore" to "Сингапур",
        "Philipsburg" to "Филипсбург",
        "Bratislava" to "Братислава",
        "Ljubljana" to "Любляна",
        "Honiara" to "Хониара",
        "Mogadishu" to "Могадишо",
        "Pretoria" to "Претория",
        "King Edward Point" to "Кинг Эдуард Пойнт",
        "Seoul" to "Сеул",
        "Juba" to "Джуба",
        "Madrid" to "Мадрид",
        "Colombo" to "Коломбо",
        "Khartoum" to "Хартум",
        "Paramaribo" to "Парамарибо",
        "Longyearbyen" to "Лонгьир",
        "Lobamba" to "Лобамба",
        "Stockholm" to "Стокгольм",
        "Bern" to "Берн",
        "Damascus" to "Дамаск",
        "Taipei" to "Тайбэй",
        "Dushanbe" to "Душанбе",
        "Dodoma" to "Додома",
        "Bangkok" to "Бангкок",
        "Dili" to "Дили",
        "Lomé" to "Ломе",
        "Fakaofo" to "Факаофа",
        "Nuku'alofa" to "Нукуалофа",
        "Port of Spain" to "Порт-оф-Спейн",
        "Tunis" to "Тунис",
        "Ankara" to "Анкара",
        "Ashgabat" to "Ашхабад",
        "Cockburn Town" to "Кокберн Таун",
        "Funafuti" to "Фунафути",
        "Kampala" to "Кампала",
        "Kiev" to "Киев",
        "Abu Dhabi" to "Абу-Даби",
        "London" to "Лондон",
        "Washington, D.C." to "Вашингтон",
        "Montevideo" to "Монтевидео",
        "Tashkent" to "Ташкент",
        "Port-Vila" to "Порт-Вила",
        "Caracas" to "Каракас",
        "Hanoi" to "Ханой",
        "Mata-Utu" to "Мата-Уту",
        "El Aaiún" to "Эль-Аюн",
        "Sana'a" to "Сана",
        "Lusaka" to "Лусака",
        "Harare" to "Хараре"
    )

}