package com.bartex.quizday.model.common

object MapOfState {
    val mapStates = mapOf(
        "Afghanistan" to "Афганистан",
        "Åland Islands" to "Аландские острова",
        "Albania" to "Албания ",
        "Algeria" to "Алжир",
        "American Samoa" to "Американское Самоа",
        "Andorra" to "Андорра",
        "Angola" to "Ангола",
        "Anguilla" to "Ангилья",
        "Antigua and Barbuda" to "Антигуа и Барбуда",
        "Argentina" to "Аргентина",
        "Armenia" to "Армения",
        "Aruba" to "Аруба",
        "Australia" to "Австралия",
        "Austria" to "Австрия",
        "Azerbaijan" to "Азербайджан",
        "Bahamas" to "Багамские острова",
        "Bahrain" to "Бахрейн",
        "Bangladesh" to "Бангладеш",
        "Barbados" to "Барбадос",
        "Belarus" to "Беларусь",
        "Belgium" to "Бельгия",
        "Benin" to "Белиз",
        "Belize" to "Бенин",
        "Bermuda" to "Бермудские острова",
        "Bhutan" to "Бутан",
        "Bolivia (Plurinational State of)" to "Боливия",
        "Bonaire, Sint Eustatius and Saba" to "Карибские Нидерланды",
        "Bosnia and Herzegovina" to "Босния и Герцеговина",
        "Botswana" to "Ботсвана",
        "Brazil" to "Бразилия",
        "British Indian Ocean Territory" to "Британская территория Индийского океана",
        "Virgin Islands (British)" to "Британские Виргинские острова",
        "Virgin Islands (U.S.)" to "Виргинские острова США",
        "Brunei Darussalam" to "Бруней",
        "Bulgaria" to "Болгария",
        "Burkina Faso" to "Буркина-Фасо",
        "Burundi" to "Бурунди",
        "Cambodia" to "Камбоджа",
        "Cameroon" to "Камерун",
        "Canada" to "Канада",
        "Cabo Verde" to "Кабо-Верде",
        "Cayman Islands" to "Каймановы острова",
        "Central African Republic" to "Центрально-Африканская республика",
        "Chad" to "Чад",
        "Chile" to "Чили",
        "China" to "Китай",
        "Christmas Island" to "Остров Рождества",
        "Cocos (Keeling) Islands" to "Кокосовые острова",
        "Colombia" to "Колумбия",
        "Comoros" to "Коморские острова",
        "Congo" to "Конго",
        "Congo (Democratic Republic of the)" to "Демократическая республика Конго",
        "Costa Rica" to "Острова Кука",
        "Cook Islands" to "Коста-Рика",
        "Croatia" to "Хорватия",
        "Cuba" to "Куба",
        "Curaçao" to "Кюрасао",
        "Cyprus" to "Кипр",
        "Czech Republic" to "Чехия",
        "Denmark" to "Дания",
        "Djibouti" to "Джибути",
        "Dominica" to "Доминика",
        "Dominican Republic" to "Доминиканская республика",
        "Ecuador" to "Эквадор",
        "Egypt" to "Египет",
        "El Salvador" to "Сальвадор",
        "Equatorial Guinea" to "Экваториальная Гвинея",
        "Eritrea" to "Эритрея",
        "Estonia" to "Эстония",
        "Ethiopia" to "Эфиопия",
        "Falkland Islands (Malvinas)" to "Фолклендские острова",
        "Faroe Islands" to "Фарерские острова",
        "Fiji" to "Фиджи",
        "Finland" to "Финляндия",
        "France" to "Франция",
        "French Guiana" to "Французская Гвиана",
        "French Polynesia" to "Французская Полинезия",
        "French Southern Territories" to "Французские южные и антарктические земли",
        "Gabon" to "Габон",
        "Gambia" to "Гамбия",
        "Georgia" to "Грузия",
        "Germany" to "Германия",
        "Ghana" to "Гана",
        "Gibraltar" to "Гибралтар",
        "Greece" to "Греция",
        "Greenland" to "Гренландия",
        "Grenada" to "Гренада",
        "Guadeloupe" to "Гваделупа",
        "Guam" to "Гуам",
        "Guatemala" to "Гватемала",
        "Guernsey" to "Гернси",
        "Guinea" to "Гвинея",
        "Guinea-Bissau" to "Гвинея-Бисау",
        "Guyana" to "Гайана",
        "Haiti" to "Гаити",
        "Vatican City" to "Ватикан",
        "Honduras" to "Гондурас",
        "Hong Kong" to "Гонконг",
        "Hungary" to "Венгрия",
        "Iceland" to "Исландия",
        "India" to "Индия",
        "Indonesia" to "Индонезия",
        "Ivory Coast" to "Кот-д,Ивуар",
        "Iran (Islamic Republic of)" to "Иран",
        "Iraq" to "Ирак",
        "Ireland" to "Ирландия",
        "Isle of Man" to "Остров Мэн",
        "Israel" to "Израиль",
        "Italy" to "Италия",
        "Jamaica" to "Ямайка",
        "Japan" to "Япония",
        "Jersey" to "Джерси",
        "Jordan" to "Иордания",
        "Kazakhstan" to "Казахстан",
        "Kenya" to "Кения",
        "Kiribati" to "Кирибати",
        "Kuwait" to "Кувейт",
        "Kyrgyzstan" to "Кыргызстан",
        "Lao People's Democratic Republic" to "Лаос",
        "Latvia" to "Латвия",
        "Lebanon" to "Ливан",
        "Lesotho" to "Лесото",
        "Liberia" to "Либерия",
        "Libya" to "Ливия",
        "Liechtenstein" to "Лихтенштейн",
        "Lithuania" to "Литва",
        "Luxembourg" to "Люксембург",
        "Macedonia (the former Yugoslav Republic of)" to "Северная Македония",
        "Madagascar" to "Мадагаскар",
        "Malawi" to "Малави",
        "Malaysia" to "Малайзия",
        "Maldives" to "Мальдивы",
        "Mali" to "Мали",
        "Malta" to "Мальта",
        "Marshall Islands" to "Маршалловы острова",
        "Martinique" to "Мартиника",
        "Mauritania" to "Мавритания",
        "Mauritius" to "Маврикий",
        "Mayotte" to "Майотта",
        "Mexico" to "Мексика",
        "Micronesia (Federated States of)" to "Федеративные Штаты Микронезии",
        "Moldova (Republic of)" to "Молдова",
        "Monaco" to "Монако",
        "Mongolia" to "Монголия",
        "Montenegro" to "Черногория",
        "Montserrat" to "Монтсеррат",
        "Morocco" to "Марокко",
        "Mozambique" to "Мозамбик",
        "Myanmar" to "Мьянма",
        "Namibia" to "Намибия",
        "Nauru" to "Науру",
        "Nepal" to "Непал",
        "Netherlands" to "Нидерланды",
        "New Caledonia" to "Новая Каледония",
        "New Zealand" to "Новая Зеландия",
        "Nicaragua" to "Никарагуа",
        "Niger" to "Нигер",
        "Nigeria" to "Нигерия",
        "Niue" to "Ниуэ",
        "Norfolk Island" to "Остров Норфолк",
        "Korea (Democratic People's Republic of)" to "Северная Корея",
        "Northern Mariana Islands" to "Северные Марианские острова",
        "Norway" to "Норвегия",
        "Oman" to "Оман",
        "Pakistan" to "Пакистан",
        "Palau" to "Палау",
        "Palestine, State of" to "Государство Палестина",
        "Panama" to "Панама",
        "Papua New Guinea" to "Папуа-Новая Гвинея",
        "Paraguay" to "Парагвай",
        "Peru" to "Перу",
        "Philippines" to "Филиппины",
        "Pitcairn" to "Острова Питкэрн",
        "Poland" to "Польша",
        "Portugal" to "Португалия",
        "Puerto Rico" to "Пуэрто-Рико",
        "Qatar" to "Катар",
        "Republic of Kosovo" to "Косово",
        "Réunion" to "Реюньон",
        "Romania" to "Румыния",
        "Russian Federation" to "Россия",
        "Rwanda" to "Руанда",
        "Saint Barthélemy" to "Сен-Бартелеми",
        "Saint Helena, Ascension and Tristan da Cunha" to "Святой Елены, Вознесения и Тристан-де-Кунья",
        "Saint Kitts and Nevis" to "Сент-Китс и Невис",
        "Saint Lucia" to "Сент-Люсия",
        "Saint Martin (French part)" to "Сен-Мартен",
        "Saint Pierre and Miquelon" to "Сен-Пьер и Микелон",
        "Saint Vincent and the Grenadines" to "Святой Винсент и Гренадины",
        "Samoa" to "Самоа",
        "San Marino" to "Сан-Марино",
        "Sao Tome and Principe" to "Сан-Томе и Принсипи",
        "Saudi Arabia" to "Саудовская Аравия",
        "Senegal" to "Сенегал",
        "Serbia" to "Сербия",
        "Seychelles" to "Сейшельские острова",
        "Sierra Leone" to "Сьерра-Леоне",
        "Singapore" to "Сингапур",
        "Sint Maarten (Dutch part)" to "Синт-Мартен",
        "Slovakia" to "Словакия",
        "Slovenia" to "Словения",
        "Solomon Islands" to "Соломоновы острова",
        "Somalia" to "Сомали",
        "South Africa" to "Южная Африка",
        "South Georgia and the South Sandwich Islands" to "Южная Георгия и Южные Сандвичевы острова",
        "Korea (Republic of)" to "Южная Корея",
        "South Sudan" to "Южный Судан",
        "Spain" to "Испания",
        "Sri Lanka" to "Шри-Ланка",
        "Sudan" to "Судан",
        "Suriname" to "Суринам",
        "Svalbard and Jan Mayen" to "Шпицберген и Ян Майен",
        "Swaziland" to "Эсватини",
        "Sweden" to "Швеция",
        "Switzerland" to "Швейцария",
        "Syrian Arab Republic" to "Сирия",
        "Taiwan" to "Тайвань",
        "Tajikistan" to "Таджикистан",
        "Tanzania, United Republic of" to "Танзания",
        "Thailand" to "Тайланд",
        "Timor-Leste" to "Восточный Тимор",
        "Togo" to "Того",
        "Tokelau" to "Токелау",
        "Tonga" to "Тонга",
        "Trinidad and Tobago" to "Тринидад и Тобаго",
        "Tunisia" to "Тунис",
        "Turkey" to "Турция",
        "Turkmenistan" to "Туркменистан",
        "Turks and Caicos Islands" to "Острова Теркс и Кайкос",
        "Tuvalu" to "Тувалу",
        "Uganda" to "Уганда",
        "Ukraine" to "Украина",
        "United Arab Emirates" to "Объединённые Арабские Эмираты",
        "United Kingdom of Great Britain and Northern Ireland" to "Великобритания",
        "United States of America" to "Соединённые Штаты Америки",
        "Uruguay" to "Уругвай",
        "Uzbekistan" to "Узбекистан",
        "Vanuatu" to "Вануату",
        "Venezuela (Bolivarian Republic of)" to "Венесуэла",
        "Vietnam" to "Вьетнам",
        "Wallis and Futuna" to "Уоллис и Футуна",
        "Western Sahara" to "Западная Сахара",
        "Yemen" to "Йемен",
        "Zambia" to "Замбия",
        "Zimbabwe" to "Зимбабве"
    )
}